# Note that mongo container is started before Orion, as Orion needs it
# as dependency and reserve the order has been found problematic in some
# low resource hosts
mongo:
  image: mongo:3.2
  container_name: mongo-test
  command: --nojournal
orion:
  image: fiware/orion
  container_name: orion-test
  links:
    - mongo
  ports:
    - "1026:1026"
  command: -dbhost mongo -logLevel DEBUG