/*
 * FIWARE-NGSI v2 Specification
 * FIWARE-NGSI v2 Specification
 *
 * OpenAPI spec version: 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package org.interiot.fiware.ngsiv2.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.interiot.fiware.ngsiv2.client.model.TypeAttributes;


/**
 * EntityType
 */

public class EntityType   {
  @SerializedName("type")
  private String type = null;

  @SerializedName("attrs")
  private TypeAttributes attrs = null;

  @SerializedName("count")
  private Integer count = null;

  public EntityType type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public EntityType attrs(TypeAttributes attrs) {
    this.attrs = attrs;
    return this;
  }

   /**
   * Get attrs
   * @return attrs
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public TypeAttributes getAttrs() {
    return attrs;
  }

  public void setAttrs(TypeAttributes attrs) {
    this.attrs = attrs;
  }

  public EntityType count(Integer count) {
    this.count = count;
    return this;
  }

   /**
   * Get count
   * @return count
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public Integer getCount() {
    return count;
  }

  public void setCount(Integer count) {
    this.count = count;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EntityType entityType = (EntityType) o;
    return Objects.equals(this.type, entityType.type) &&
        Objects.equals(this.attrs, entityType.attrs) &&
        Objects.equals(this.count, entityType.count);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, attrs, count);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EntityType {\n");
    
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    attrs: ").append(toIndentedString(attrs)).append("\n");
    sb.append("    count: ").append(toIndentedString(count)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

